### ISSUE TITLE
get random outs is not returning anything quite often

### ISSUE THREAD

**Issue by ExtraHash** [TurtlePay/blockchain-cache-api#7]
Still trying to troubleshoot all of these transaction creation errors, it appears like quite alot, when I end a transaction, the cache is not returning any random outs. As a result, the transaction fails.

![image](https://user-images.githubusercontent.com/35851667/64558657-9e8d5000-d301-11e9-95db-6a127e11fa56.png)

![image](https://user-images.githubusercontent.com/35851667/64558610-83224500-d301-11e9-98a4-c91c89153005.png)

this is the code and the logging i've added, it seems like it might just be returning an empty array for randomOuts.

**Comment by zpalmtree** [comment]
You probably want to be logging here instead: https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/Daemon.ts#L402 to get the error message if any.

**Comment by ExtraHash** [comment]
Ok, I logged the error there and it is not returning any error

**Comment by brandonlehmann** [comment]
Can you give the amounts requested so that I can mimic the request?

**Comment by zpalmtree** [comment]
Reminder that TRACE debugging will now show request params+responses for your convenience

**Comment by ExtraHash** [comment]
It looks like this may be related to the ESOCKETTIMEOUT error...

```
[Mon, 09 Sep 2019 20:21:58 GMT] [Trace] [Daemon]: Making request to /randomOutputs with params {"amounts":[7,70,800,9000,60000,200000,8000000,60000000],"mixin":4}
[Mon, 09 Sep 2019 20:21:58 GMT] [Error] [Transactions] [Daemon]: Failed to get random outs: RequestError: Error: ESOCKETTIMEDOUT
```

**Comment by brandonlehmann** [comment]
ESOCKETTIMEDOUT is client side not cache side.
